fresha/api-tools

package-lock.json
packages/json-schema-model/package.json
packages/json-schema-model/src/AllOfSchema.ts
packages/json-schema-model/src/AnyOfSchema.ts
packages/json-schema-model/src/ArraySchema.ts
packages/json-schema-model/src/BooleanSchema.ts
packages/json-schema-model/src/NotSchema.ts
packages/json-schema-model/src/NumberSchema.ts
packages/json-schema-model/src/ObjectSchema.ts
packages/json-schema-model/src/OneOfSchema.ts
packages/json-schema-model/src/Reference.ts
packages/json-schema-model/src/Registry.test.ts
packages/json-schema-model/src/Registry.ts
packages/json-schema-model/src/SchemaBase.ts
packages/json-schema-model/src/SchemaReader.test.ts
packages/json-schema-model/src/SchemaReader.ts
packages/json-schema-model/src/SchemaWriter.test.ts
packages/json-schema-model/src/SchemaWriter.ts
packages/json-schema-model/src/StringSchema.ts
packages/json-schema-model/src/index.ts
packages/json-schema-model/src/types.ts

This PR adds the @fresha/json-schema-model package that implements object model for JSON Schema (core + validation).

Add @fresha/json-schema-model package

---

packages/api-tools-core/LICENSE
packages/api-tools-core/README.md
packages/api-tools-core/package.json
packages/api-tools-core/src/index.ts
packages/api-tools-core/src/typeGuards.test.ts
packages/api-tools-core/src/typeGuards.ts
packages/api-tools-core/src/types.ts

This PR adds generic JSON:API type definitions and type guards.

Prepare api-tools-core@0.1.0

---

package-lock.json
packages/api-tools-core/src/types.ts
packages/har-extract/.eslintrc
packages/har-extract/README.md
packages/har-extract/bin/cli.js
packages/har-extract/jest.config.js
packages/har-extract/package.json
packages/har-extract/src/cli.ts
packages/har-extract/src/index.test.ts
packages/har-extract/src/index.ts
packages/har-extract/src/types.ts
packages/har-extract/tsconfig.eslint.json
packages/har-extract/tsconfig.json

This PR adds `fresha-har-extract` CLI script. One can use it for extracting from HAR files the structure of JSON:API requests and responses.

Implement fresha-har-extract CLI command

---

README.md
docs/CODING.md

This PR moves basic project documentation from my private project.

Port basic documentation from https://github.com/mykulyak/api-tools-private

---

package-lock.json
packages/api-tools-core/README.md
packages/api-tools-core/package.json
packages/har-extract/package.json
packages/json-api-model/package.json
packages/json-schema-model/package.json
packages/openapi-model/package.json

This PR adds more information to the `@fresha/api-tools-core`'s `README.md` file, as well as bumps package version to 0.2.0.

@fresha/api-tools-core v0.2.0

---

package-lock.json
packages/openapi-model/README.md
packages/openapi-model/package.json

This PR adds README file to `@fresha/openapi-model` package, as well as bumps package version to `0.2.0`.

Add README.md + bump version of @fresha/openapi-model

---

.circleci/config.yml
docs/CODEGEN.md
package-lock.json
packages/openapi-codegen-server-nestjs/README.md
packages/openapi-codegen-server-nestjs/package.json
packages/openapi-codegen-server-nestjs/src/Action.ts
packages/openapi-codegen-server-nestjs/src/ActionParam.ts
packages/openapi-codegen-server-nestjs/src/Controller.test.ts
packages/openapi-codegen-server-nestjs/src/Controller.ts
packages/openapi-codegen-server-nestjs/src/DTO.test.ts
packages/openapi-codegen-server-nestjs/src/DTO.ts
packages/openapi-codegen-server-nestjs/src/Generator.test.ts
packages/openapi-codegen-server-nestjs/src/Generator.ts
packages/openapi-codegen-server-nestjs/src/Module.ts
packages/openapi-codegen-server-nestjs/src/index.test.ts
packages/openapi-codegen-server-nestjs/src/index.ts
packages/openapi-codegen-server-nestjs/src/utils/index.ts
packages/openapi-codegen-server-nestjs/src/utils/lodash.ts
packages/openapi-codegen-server-nestjs/src/utils/nest.ts
packages/openapi-codegen-server-nestjs/src/utils/openapi.ts
packages/openapi-codegen-server-nestjs/src/utils/ts.test.ts
packages/openapi-codegen-server-nestjs/src/utils/ts.ts
packages/openapi-codegen-server-nestjs/src/utils/utils.test.ts
packages/openapi-codegen-server-nestjs/src/utils/utils.ts
packages/openapi-codegen-server-nestjs/tsconfig.json
packages/openapi-codegen/README.md
packages/openapi-codegen/bin/fresha-openapi-codegen.js
packages/openapi-codegen/package.json
packages/openapi-codegen/src/index.ts

This PR implements (most of) OpenAPI code generator for NestJS projects.
Implementation status

OpenAPI code generators for NestJS servers - p.1

---

.circleci/config.yml
package-lock.json
packages/openapi-codegen-server-elixir/README.md
packages/openapi-codegen-server-elixir/package.json
packages/openapi-codegen-server-elixir/src/Action.ts
packages/openapi-codegen-server-elixir/src/Controller.ts
packages/openapi-codegen-server-elixir/src/Generator.ts
packages/openapi-codegen-server-elixir/src/Resource.ts
packages/openapi-codegen-server-elixir/src/Router.ts
packages/openapi-codegen-server-elixir/src/index.ts
packages/openapi-codegen-server-elixir/src/utils.ts
packages/openapi-codegen/package.json
packages/openapi-codegen/src/index.ts

This PR adds skeleton code of Elixir code generator.
None.

OpenAPI code generators for Elixir (Phoenix) servers - p.1

---

package-lock.json
packages/asyncapi-model/package.json
packages/asyncapi-model/src/index.ts
packages/asyncapi-model/src/v2.4.0/index.ts
packages/asyncapi-model/src/v2.4.0/types/bindings/amqp.ts
packages/asyncapi-model/src/v2.4.0/types/bindings/amqp1.ts
packages/asyncapi-model/src/v2.4.0/types/bindings/anypointmq.ts
packages/asyncapi-model/src/v2.4.0/types/bindings/http.ts
packages/asyncapi-model/src/v2.4.0/types/bindings/ibmmq.ts
packages/asyncapi-model/src/v2.4.0/types/bindings/jms.ts
packages/asyncapi-model/src/v2.4.0/types/bindings/kafka.ts
packages/asyncapi-model/src/v2.4.0/types/bindings/mercure.ts
packages/asyncapi-model/src/v2.4.0/types/bindings/mqtt.ts
packages/asyncapi-model/src/v2.4.0/types/bindings/mqtt5.ts
packages/asyncapi-model/src/v2.4.0/types/bindings/nats.ts
packages/asyncapi-model/src/v2.4.0/types/bindings/redis.ts
packages/asyncapi-model/src/v2.4.0/types/bindings/sns.ts
packages/asyncapi-model/src/v2.4.0/types/bindings/solace.ts
packages/asyncapi-model/src/v2.4.0/types/bindings/sqs.ts
packages/asyncapi-model/src/v2.4.0/types/bindings/stomp.ts
packages/asyncapi-model/src/v2.4.0/types/bindings/ws.ts
packages/asyncapi-model/src/v2.4.0/types/index.ts

Similarly to OpenAPI, tooling for message-based APIs should base on some common model. This PR implements the first part of the model package, typings for AsyncAPI spec v2.5.0.

Typings for @fresha/asyncapi-model

---

package-lock.json
packages/asyncapi-model/package.json
packages/har-extract/package.json
packages/json-api-model/package.json
packages/json-schema-model/package.json
packages/openapi-model/package.json

This is a housekeeping PR. It bumps version of `@fresha/api-tools-core` to the latest published one (0.2.1).
None.

Update @fresha/api-tools-core dependency version to 0.2.1

---

package-lock.json
packages/openapi-codegen-client-typescript/package.json
packages/openapi-codegen-server-elixir/package.json
packages/openapi-codegen-server-nestjs/package.json
packages/openapi-model/package.json

This PS bumps package version of `@fresha/openapi-model` to `0.3.0`, thus preparing for release.
None.

Bump version of openapi-model to 0.3.0

---

.circleci/config.yml
package-lock.json
packages/openapi-codegen-cli/src/index.ts
packages/openapi-codegen-server-mock/.eslintrc
packages/openapi-codegen-server-mock/README.md
packages/openapi-codegen-server-mock/jest.config.js
packages/openapi-codegen-server-mock/package.json
packages/openapi-codegen-server-mock/src/Generator.ts
packages/openapi-codegen-server-mock/src/command.ts
packages/openapi-codegen-server-mock/src/index.test.ts
packages/openapi-codegen-server-mock/src/index.ts
packages/openapi-codegen-server-mock/tsconfig.eslint.json
packages/openapi-codegen-server-mock/tsconfig.json

We need code generator that creates mock API servers. As runtime support library I chose Mirage.js.
None.

Initialize openapi-codegen-server-mock package

---

.circleci/config.yml
package-lock.json
packages/openapi-codegen-utils/.eslintrc
packages/openapi-codegen-utils/jest.config.js
packages/openapi-codegen-utils/package.json
packages/openapi-codegen-utils/src/index.test.ts
packages/openapi-codegen-utils/src/index.ts
packages/openapi-codegen-utils/src/logging.ts
packages/openapi-codegen-utils/src/openapi.test.ts
packages/openapi-codegen-utils/src/openapi.ts
packages/openapi-codegen-utils/src/string.test.ts
packages/openapi-codegen-utils/src/string.ts
packages/openapi-codegen-utils/src/tsMorph.test.ts
packages/openapi-codegen-utils/src/tsMorph.ts
packages/openapi-codegen-utils/tsconfig.eslint.json
packages/openapi-codegen-utils/tsconfig.json

This PR extracts shared code from code generators and place it in a single package, `@fresha/openapi-codegen-utils`.
None.

Add @fresha/openapi-codegen-utils package

---

package-lock.json
packages/openapi-codegen-client-fetch/package.json
packages/openapi-codegen-client-fetch/src/Generator.ts
packages/openapi-codegen-client-fetch/src/command.ts
packages/openapi-codegen-utils/src/openapi.ts

Openapi codegen client fetch

---

package-lock.json
packages/openapi-codegen-client-fetch/src/command.ts
packages/openapi-codegen-server-mock/package.json
packages/openapi-codegen-server-mock/src/Generator.ts
packages/openapi-codegen-server-mock/src/command.ts

This PR implements a 'server-mock' code generator, based on Mirage.js.
Methods are not yet filled with code.

Implement @fresha/openapi-codegen-server-mock

---

packages/openapi-codegen-client-fresha/src/parts/ActionSignature.ts
packages/openapi-codegen-server-nestjs/src/DTO.test.ts
packages/openapi-codegen-server-nestjs/src/DTO.ts
packages/openapi-codegen-server-nestjs/src/Generator.test.ts
packages/openapi-codegen-utils/src/jsonapi.ts
packages/openapi-model/src/3.0.3/model/Schema.test.ts
packages/openapi-model/src/3.0.3/model/Schema.ts
packages/openapi-model/src/3.0.3/model/types.ts
packages/openapi-model/src/3.0.3/types.ts

This PR addresses https://github.com/fresha/api-tools/issues/57.
None.

Extend SchemaModel

---

examples/codegen/elixir_api/README.md

This PR adds basic documentation for example Elixir application.
None.

Add docs for example Elixir application

---

.circleci/config.yml
package-lock.json
packages/ex-morph/.eslintrc
packages/ex-morph/LICENSE
packages/ex-morph/README.md
packages/ex-morph/jest.config.js
packages/ex-morph/package.json
packages/ex-morph/src/Project.test.ts
packages/ex-morph/src/Project.ts
packages/ex-morph/src/SourceFile.test.ts
packages/ex-morph/src/SourceFile.ts
packages/ex-morph/src/index.ts
packages/ex-morph/src/testHelpers.ts
packages/ex-morph/src/utils.test.ts
packages/ex-morph/src/utils.ts
packages/ex-morph/tsconfig.eslint.json
packages/ex-morph/tsconfig.json

This PR extracts code that generates Elixir code, to a separate package `@fresha/ex-morph`. Later it will be used in several places, e.g. in AsyncAPI code generators.
None.

Extract elixir code build to @fresha/ex-morph

---

packages/ex-morph/src/Project.ts
packages/ex-morph/src/SourceFile.ts
packages/openapi-codegen-server-elixir/src/command.ts
packages/openapi-codegen-server-elixir/src/parts/Controller.test.ts
packages/openapi-codegen-server-elixir/src/parts/Controller.ts
packages/openapi-codegen-server-elixir/src/parts/ControllerTestSuite.ts
packages/openapi-codegen-server-elixir/src/parts/FallbackController.ts
packages/openapi-codegen-server-elixir/src/parts/Generator.ts
packages/openapi-codegen-server-elixir/src/parts/Resource.ts
packages/openapi-codegen-server-elixir/src/parts/ResourceTestSuite.ts
packages/openapi-codegen-server-elixir/src/parts/Router.test.ts
packages/openapi-codegen-server-elixir/src/parts/Router.ts
packages/openapi-codegen-server-elixir/src/parts/View.ts
packages/openapi-codegen-server-elixir/src/parts/ViewTestSuite.ts
packages/openapi-codegen-server-elixir/src/parts/types.ts
packages/openapi-codegen-server-elixir/src/testHelpers.ts

- routing configuration was wrong
- messages were not optimal in some cases

Improve elixir openapi codegen

---

examples/codegen/run.sh
package-lock.json
packages/api-tools-core/package.json
packages/asyncapi-model/package.json
packages/ex-morph/package.json
packages/har-extract/package.json
packages/json-api-model/package.json
packages/json-schema-model/package.json
packages/openapi-codegen-cli/package.json
packages/openapi-codegen-client-fetch/package.json
packages/openapi-codegen-client-fresha/package.json
packages/openapi-codegen-server-elixir/README.md
packages/openapi-codegen-server-elixir/package.json
packages/openapi-codegen-server-mock/package.json
packages/openapi-codegen-server-nestjs/package.json
packages/openapi-codegen-utils/package.json
packages/openapi-model/package.json

Need to publish modified packages.
None.

Prepare release

---

.circleci/config.yml
package-lock.json
packages/openapi-codegen-cli/src/index.ts
packages/openapi-codegen-docs/.eslintrc
packages/openapi-codegen-docs/README.md
packages/openapi-codegen-docs/jest.config.js
packages/openapi-codegen-docs/package.json
packages/openapi-codegen-docs/src/command.ts
packages/openapi-codegen-docs/src/index.test.ts
packages/openapi-codegen-docs/src/index.ts
packages/openapi-codegen-docs/src/parts/Generator.ts
packages/openapi-codegen-docs/src/parts/index.ts
packages/openapi-codegen-docs/tsconfig.eslint.json
packages/openapi-codegen-docs/tsconfig.json
packages/openapi-model/src/3.0.3/model/PathItem.ts

This PR starts documentation generator specific to JSON:API.

Add (experimental) docs-json-api OpenAPI generator

---

package-lock.json
packages/json-api-model/package.json
packages/openapi-codegen-client-fetch/package.json
packages/openapi-codegen-client-fresha/package.json
packages/openapi-codegen-docs/package.json
packages/openapi-codegen-server-elixir/package.json
packages/openapi-codegen-server-mock/package.json
packages/openapi-codegen-server-nestjs/package.json
packages/openapi-codegen-test-utils/package.json
packages/openapi-codegen-utils/package.json
packages/openapi-lint/package.json
packages/openapi-model/package.json

This PR bumps version of @fresha/openapi-model to 0.5.0, and updates dependency versions of its dependants.
N/A

Release @fresha/openapi-model@0.5.0

---

README.md
lerna.json
nx.json
package-lock.json
package.json

This PR introduces Lerna, which solves several problems:
- package commands are run in correct order, taking into account package dependencies
- commands are cached, that improves their execution speed (up to ~10 times)
- package publishing became much simpler as well (only one command is necessary)
N/A.

Set up lerna

---

packages/asyncapi-codegen-client-typescript/README.md
packages/asyncapi-codegen-server-elixir/README.md
packages/asyncapi-codegen-server-nestjs/README.md
packages/asyncapi-codegen/README.md
packages/asyncapi-diff/README.md
packages/asyncapi-lint/README.md
packages/asyncapi-model/README.md
packages/asyncapi-validator/README.md
packages/code-morph-ex/README.md
packages/code-morph-test-utils/README.md
packages/code-morph-ts/README.md
packages/designer-app/README.md
packages/designer-web/README.md
packages/json-api-codegen/README.md
packages/json-schema-codegen/README.md
packages/json-schema-model/README.md
packages/openapi-codegen-test-utils/README.md
packages/openapi-codegen-utils/README.md
packages/openapi-diff/README.md
packages/openapi-lint/README.md
packages/openapi-validator/README.md
tools/eslint-config/README.md
tools/jest-config/README.md
tools/typescript-config/README.md

This PR adds missing README files.
N/A.

Add missing README files

---

.github/workflows/check.yml
.github/workflows/openapi_codegen.yml
examples/codegen/client_fetch/package.json
examples/codegen/client_fetch/src/index.js
examples/codegen/client_fetch/tsconfig.json
examples/codegen/mock_api/package.json
examples/codegen/mock_api/src/index.js
examples/codegen/mock_api/tsconfig.json
examples/openapi-codegen-test-api.yaml

Add integration tests for OpenAPI code generators

---

packages/openapi-codegen-client-fetch/src/parts/ActionFunc.test.ts
packages/openapi-codegen-client-fetch/src/parts/ActionFunc.ts
packages/openapi-codegen-client-fetch/src/parts/UtilsFile.ts
packages/openapi-codegen-client-fetch/src/parts/utils.ts

Add response transformer

---

examples/openapi-codegen-test-api.yaml
packages/openapi-codegen-client-fetch/src/parts/ActionFunc.test.ts
packages/openapi-codegen-client-fetch/src/parts/ActionFunc.ts
packages/openapi-codegen-client-fetch/src/parts/UtilsFile.ts
packages/openapi-codegen-client-fetch/src/parts/__snapshots__/ActionFunc.test.ts.snap

The support for optional header parameters turned out to be broken.
This PR adds the case to the test schema and also migrates some of the tests to snapshots
- [ x] Bug fix (non-breaking change which fixes an issue)

Use snapshot and test support for optional header parameters

---

package-lock.json
packages/openapi-codegen-cli/package.json
packages/openapi-codegen-client-fetch/package.json

Bump and publish packages

---

package-lock.json
packages/openapi-codegen-client-fetch/package.json
packages/openapi-codegen-client-fetch/src/parts/ActionFunc.test.ts
packages/openapi-codegen-server-elixir/package.json
packages/openapi-codegen-server-elixir/src/parts/Controller.test.ts
packages/openapi-codegen-server-elixir/src/parts/Resource.test.ts
packages/openapi-codegen-server-elixir/src/parts/ResourceTestSuite.test.ts
packages/openapi-codegen-server-elixir/src/parts/Router.test.ts
packages/openapi-codegen-server-elixir/src/parts/__snapshots__/Controller.test.ts.snap
packages/openapi-codegen-server-elixir/src/parts/__snapshots__/Resource.test.ts.snap
packages/openapi-codegen-server-elixir/src/parts/__snapshots__/ResourceTestSuite.test.ts.snap
packages/openapi-codegen-server-elixir/src/parts/__snapshots__/Router.test.ts.snap
packages/openapi-codegen-server-nestjs/package.json
packages/openapi-codegen-server-nestjs/src/ActionParam.test.ts
packages/openapi-codegen-server-nestjs/src/DTO.test.ts
packages/openapi-codegen-server-nestjs/src/__snapshots__/ActionParam.test.ts.snap
packages/openapi-codegen-server-nestjs/src/__snapshots__/DTO.test.ts.snap

This PR replaces inline texts with Jest snapshots. It unclutters test files, thus allowing us to write tests more efficiently.
N/A.

Replace elixir codegen tests with snapshot tests
