fresha/api-tools

packages/api-tools-core/package.json, packages/asyncapi-codegen-client-typescript/package.json, packages/asyncapi-codegen-server-elixir/package.json, packages/asyncapi-codegen-server-nestjs/package.json, packages/asyncapi-codegen/package.json, packages/asyncapi-diff/package.json, packages/asyncapi-lint/package.json, packages/asyncapi-model/package.json, packages/asyncapi-validator/package.json, packages/designer-app/package.json, packages/designer-devtools/package.json, packages/designer-web/package.json, packages/har-extract/package.json, packages/json-api-codegen/package.json, packages/json-api-model/package.json, packages/json-schema-codegen/package.json, packages/json-schema-model/package.json, packages/openapi-codegen-client-typescript/package.json, packages/openapi-codegen-server-elixir/package.json, packages/openapi-codegen-server-nestjs/package.json, packages/openapi-codegen/package.json, packages/openapi-diff/package.json, packages/openapi-lint/package.json, packages/openapi-model/package.json, packages/openapi-validator/package.json
This PR adds `clean` NPM script for project's packages. The script is automatically run before `build` and `build:watch` commands.
=> Add clean, prebuild and prebuild:watch common NPM scripts

.github/PULL_REQUEST_TEMPLATE.md, package-lock.json, packages/openapi-model/docs/index.md, packages/openapi-model/package.json, packages/openapi-model/src/3.0.3/index.ts, packages/openapi-model/src/3.0.3/types.test.ts, packages/openapi-model/src/3.0.3/types.ts, packages/openapi-model/src/3.1.0/index.ts, packages/openapi-model/src/3.1.0/types.ts, packages/openapi-model/src/baseTypes.ts, packages/openapi-model/src/index.test.ts, packages/openapi-model/src/index.ts
This PR adds TypeScript typings for structures defined in OpenAPI specifications v3.0 and v3.1. Typings will be part of the `@fresha/openapi-model` package.
None
=> Add TS typings for OpenAPI spec (v3.x)

packages/openapi-model/package.json
This PR defines `files` in `package.json` of the `@fresha/openapi-model`, so that only transpiled files are included in the release.
None.
=> Prepare to publish openapi-model@0.1.0

package-lock.json, tools/jest-config/.eslintrc, tools/jest-config/package.json, tools/jest-config/src/index.ts, tools/jest-config/src/setupEnv.ts, tools/jest-config/src/types.ts, tools/jest-config/tsconfig.eslint.json, tools/jest-config/tsconfig.json
There's a need of externalising test matcher code from packages that use it. For example, we need to test whether the source code text generated by our tools is the same as expected.
This PR extends @fresha/jest-config with a toHaveFormattedCode() matcher, which compares 2 versions of source code (to minimise the amount of false positives, it uses prettier to normalise the code).
=> Extend @fresha/jest-config with custom matcher

packages/openapi-model/examples/json-api.yaml, packages/openapi-model/src/3.0.3/model/Components.test.ts, packages/openapi-model/src/3.0.3/model/Components.ts, packages/openapi-model/src/3.0.3/model/OpenAPI.ts, packages/openapi-model/src/3.0.3/model/OpenAPIReader.test.ts, packages/openapi-model/src/3.0.3/model/OpenAPIReader.ts, packages/openapi-model/src/3.0.3/model/OpenAPIWriter.test.ts, packages/openapi-model/src/3.0.3/model/OpenAPIWriter.ts, packages/openapi-model/src/3.0.3/model/PathItem.ts, packages/openapi-model/src/3.0.3/model/Schema.test.ts, packages/openapi-model/src/3.0.3/model/Schema.ts, packages/openapi-model/src/3.0.3/model/index.ts, packages/openapi-model/src/3.0.3/model/types.test.ts, packages/openapi-model/src/3.0.3/model/types.ts, packages/openapi-model/src/3.0.3/types.ts, packages/openapi-model/src/3.1.0/types.ts
During work on NestJS code generators, the following bugs had to be fixed:
- proper handling of multi-level references in OpenAPI schemas (e.g. `PathItem` -> `RequestBody` -> `Schema` -> `Schema`)
- `Components.securitySchemas` was renamed to securitySchemes, according to the specification
- exposed `OpenAPIFactory` interface, to allow creation of OpenAPI models
- proper handling of `SchemaModel.exclusiveMaximum` and `SchemaModel.exclusiveMinimum`
- `PathItem.addOperation` was renamed to `PathItem.setOperation`, according to guidelines
- creation parameters of `SchemaModel` were unified among all factory methods of `Schema`
- `SchemaFactory` has been exposed, to allow creation of schema instances
- added `Schema.addOneOf`, `Schema.deleteOneOf` and `Schema.clearOneOf` methods
=> Extend/fix @fresha/openapi-model

package-lock.json, packages/openapi-model/package.json
This PR removes `@fresha/json-schema-model` dependency from `@fresha/openapi-model`. It also bumps package version of the latter.
=> Remove unused dependency from openapi-model

package-lock.json, packages/openapi-codegen/package.json
Bump package version for `@fresha/openapi-codegen`, to include Elixir codegen.
=> Bump version for @fresha/openapi-codegen

.circleci/config.yml, package-lock.json, packages/openapi-codegen-client-typescript/src/index.ts, packages/openapi-codegen/package.json, packages/openapi-codegen/src/index.ts
This PR:
- registers `client-typescript` codegen
- bumps `openapi-codegen` version, in order to publish it
=> Bump openapi-codegen version + register TS codegen

packages/api-tools-core/README.md, packages/api-tools-core/package.json, packages/api-tools-core/src/index.ts, packages/api-tools-core/src/typeGuards.test.ts, packages/api-tools-core/src/typeGuards.ts, packages/api-tools-core/src/utils.test.ts, packages/api-tools-core/src/utils.ts
This PR ports missing types, guards and functions from `@fresha/noname-core`, which is a preparation step for moving other noname packages.
- added type guards `isJSONObject`, `isJSONValueArray`
- added string modification functions `camelCase`, `kebabCase`
- added JSON modification functions `kebabCaseDeep`, `camelCaseDeep`, `transformKeysDeep`
=> Port missing stuff from @fresha/noname-core

packages/api-tools-core/src/utils.test.ts, packages/api-tools-core/src/utils.ts, packages/openapi-codegen-client-fetch/package.json, packages/openapi-codegen-client-fetch/src/Generator.ts, packages/openapi-codegen-client-fresha/src/parts/ActionSignature.ts, packages/openapi-codegen-client-fresha/src/parts/ActionsSignatures.ts, packages/openapi-codegen-server-nestjs/src/Action.ts, packages/openapi-codegen-server-nestjs/src/Controller.ts, packages/openapi-codegen-server-nestjs/src/DTO.ts, packages/openapi-codegen-utils/src/string.test.ts, packages/openapi-codegen-utils/src/string.ts
This PR moves `titleCase` and `snakeCase` from `@fresha/openapi-codegen-utils` to `@fresha/api-tools-core`. These functions will be used in several places other than code generators.
None.
=> Move string conversion functions to @fresha/api-tools-core

examples/codegen/elixir_api/test/support/factory.ex, examples/openapi-codegen-test-api.yaml, packages/openapi-codegen-server-elixir/src/parts/Router.ts, packages/openapi-codegen-utils/src/string.test.ts, packages/openapi-codegen-utils/src/string.ts
I needed more representative OpenAPI schema for testing. Therefore, I added 2 operations that represent an API to the export job queue.
Also, a minor fix in generated routes has been fixed.
None.
=> Extend example openapi schema

packages/api-tools-core/src/typeGuards.test.ts, packages/api-tools-core/src/types.test.ts, packages/api-tools-core/src/types.ts
This PR allows for more strict typing of JSON:API resources and documents.
- JSON:API type aliases were replaced with interfaces (for better performance and diagnostics)
- `JSONAPIResourceID` became a generic, parametrised by resource type string
- `JSONAPIResourceRelationship0`, `JSONAPIResourceRelationship1` and `JSONAPIResourceRelationshipN` were added, to represent specific type of relationships. All of them are parametrised by resource type string
- `JSONAPIResourceRelationship` became a generic, parametrised by resource type string
- `JSONAPIResource`, `JSONAPIServerResource ` and `JSONAPIServerResource` became generics, parametrised by
- resource type string
- attributes' type
- relationships …
=> Better typing of JSON:API entities

packages/openapi-model/src/3.0.3/model/Callback.test.ts, packages/openapi-model/src/3.0.3/model/Callback.ts, packages/openapi-model/src/3.0.3/model/Components.ts, packages/openapi-model/src/3.0.3/model/OpenAPI.test.ts, packages/openapi-model/src/3.0.3/model/OpenAPI.ts, packages/openapi-model/src/3.0.3/model/OpenAPIWriter.test.ts, packages/openapi-model/src/3.0.3/model/Operation.test.ts, packages/openapi-model/src/3.0.3/model/Operation.ts, packages/openapi-model/src/3.0.3/model/PathItem.test.ts, packages/openapi-model/src/3.0.3/model/PathItem.ts, packages/openapi-model/src/3.0.3/model/Paths.test.ts, packages/openapi-model/src/3.0.3/model/Paths.ts, packages/openapi-model/src/3.0.3/model/types.ts, packages/openapi-model/src/BidiMap.test.ts, packages/openapi-model/src/BidiMap.ts
This PR addresses https://github.com/fresha/api-tools/issues/56 and https://github.com/fresha/api-tools/issues/44.
- added `httpMethod` property to `OperationModel`.
- added `pathUrl` property to `PathItemModel`
- added `getOperationKey()` / `getOperationKeyOrThrow()` methods to `PathItemModel`
- added `getItemUrl()` / `getItemUrlOrThrow()` methods to `PathsModel` and `CallbackModel`
- added more unit tests
=> Add PathItem.pathUrl and Operation.httpMethod

package-lock.json, packages/api-tools-core/package.json, packages/api-tools-core/src/typeGuards.test.ts, packages/api-tools-core/src/typeGuards.ts, packages/api-tools-core/src/types.ts
This PR improves TS types for `JSONAPIDataDocument`. Now, type of document's primary data is the same as defined.
```ts
type Doc = JSONAPIDataDocument<JSONAPIResource[]>;
type PrimaryData = Doc['data']; // resolves to JSONAPIResource[];
```
N/A.
=> Better TS definitions for JSONAPIDataDocument

.circleci/config.yml, package-lock.json, packages/code-morph-ex/jest.config.js, packages/code-morph-ex/package.json, packages/code-morph-ex/src/SourceFile.test.ts, packages/code-morph-ex/src/index.ts, packages/code-morph-ex/src/testHelpers.ts, packages/code-morph-test-utils/.eslintrc, packages/code-morph-test-utils/jest.config.js, packages/code-morph-test-utils/package.json, packages/code-morph-test-utils/src/elixir.ts, packages/code-morph-test-utils/src/index.ts, packages/code-morph-test-utils/src/jestConfig.ts, packages/code-morph-test-utils/src/matchers.ts, packages/code-morph-test-utils/src/setupEnv.ts, packages/code-morph-test-utils/tsconfig.eslint.json, packages/code-morph-test-utils/tsconfig.json, packages/openapi-codegen-server-elixir/jest.config.js, packages/openapi-codegen-server-elixir/package.json, packages/openapi-codegen-server-elixir/src/parts/Controller.test.ts, packages/openapi-codegen-server-elixir/src/parts/Resource.test.ts, packages/openapi-codegen-server-elixir/src/parts/Router.test.ts
This PR aim is improved DX in testing code morphers. It adds the `@fresha/code-morph-test-utils` package, where all shared testing code will reside. The package will contain Jest matchers, set up code, and similar stuff.
`@fresha/code-morph-test-utils` contains 2 Jest matchers. Also, OpenAPI code generator for Elixir uses this package.
=> Add code-morph-test-utils package

packages/openapi-codegen-utils/src/jsonapi.test.ts, packages/openapi-model/examples/petstore.yaml, packages/openapi-model/src/3.0.3/model/Components.ts, packages/openapi-model/src/3.0.3/model/OpenAPIWriter.test.ts
This PR makes `Components.setSchema` to set schema title to the key it is associated with. It adds some convenience when working with code generators.
Some unit tests have to be adapted.
=> ComponentsModel.setSchema now sets schema title

packages/openapi-model/src/3.0.3/model/Schema.test.ts, packages/openapi-model/src/3.0.3/model/Schema.ts, packages/openapi-model/src/3.0.3/model/types.ts
This PR adds several convenience methods to `SchemaModel` in `@fresha/openapi-model`. They will be used in multiple places, most notably in code generators.
Methods added:
- `.isNull()`
- `.isComposite()`
- `.addAnyOf()`
- `.deleteAnyOfAt()`
- `.clearAnyOf()`
=> Add convenience methods to SchemaModel class

package-lock.json, packages/json-api-model/src/Registry.ts, packages/json-api-model/src/Resource.ts, packages/openapi-codegen-client-fresha/src/parts/ActionSignature.ts, packages/openapi-codegen-server-elixir/src/parts/Action.ts, packages/openapi-codegen-server-elixir/src/parts/Controller.test.ts, packages/openapi-codegen-server-elixir/src/parts/Resource.test.ts, packages/openapi-codegen-test-utils/src/index.ts, packages/openapi-codegen-test-utils/src/mocks/buildEmployeeSchemasForTesting.ts, packages/openapi-codegen-test-utils/src/mocks/index.ts, packages/openapi-codegen-utils/package.json, packages/openapi-codegen-utils/src/jsonapi.test.ts, packages/openapi-codegen-utils/src/jsonapi.ts, packages/openapi-codegen-utils/src/openapi.test.ts, packages/openapi-codegen-utils/src/openapi.ts, packages/openapi-model/src/3.0.3/model/Schema.test.ts, packages/openapi-model/src/3.0.3/model/Schema.ts, packages/openapi-model/src/3.0.3/model/types.ts
This PR adds new (and refactors existing) convenience methods in `@fresha/openapi-codegen-utils`, aimed to simplify creation of `SchemaModel` objects representing JSON:API structures, like resources or documents.
- `SchemaModel.getPropertiesDeep`
- `SchemaModel.getPropertyDeep`
- `SchemaModel.getPropertyDeepOrThrow`
- `getOperationResponseSchemas`
- `getSchemaMultiProperty`
- `getSchemaProperties`
- `buildEmployeeSchemasForTesting`
- `createNullSchema`
- `setResourceIdSchema`
- `createResourceIdSchema`
- `setResourceSchema`
- `createResourceSchema`
- `addResourceAttribute`
- `addResourceAttributes`
- `addResourceRelationship`
- `addResourceRelationships`
- `setDataDocumentSchema`
- …
=> Add convenience methods related to SchemaModel handling

packages/openapi-model/src/3.0.3/model/OpenAPIWriter.ts, packages/openapi-model/src/3.0.3/model/Operation.test.ts, packages/openapi-model/src/3.0.3/model/Operation.ts, packages/openapi-model/src/3.0.3/model/types.ts
This PR fixes the bug in treating `OperationModel.security` field. Before it was not possible to distinguish between empty list of sequrity requirements and absence thereof. Therefore, it was not possible to override default security requirements for specific operation.
- `OperationModel.security` became nullable. If it is `null`, the operation uses default security requirements
- `OperationModel.getSecurityRequirements()` was added, which returns the resolved requirements
- `OperationModel.resetSecurityRequirements()` was added, which makes the operation use default requirements
```ts
const operation = ... // uses default requirements
const req1 = operation.addSecurityRequirement(); // from now on, …
```
=> Made OperationModel.security nullable

packages/api-tools-core/src/types.test.ts, packages/api-tools-core/src/types.ts
This PR adds the `JSONAPIClientDocument` type, to specifically represent client-originating (i.e. request) JSON:API documents. The difference is in the primary data and include types. In client documents, they must extend the `JSONAPIClientResource` instead of `JSONAPIServerResource`.
N/A.
=> Add JSONAPIClientDocument definition

packages/openapi-codegen-client-fetch/src/Generator.ts, packages/openapi-codegen-client-fetch/src/parts/ActionFunc.test.ts, packages/openapi-codegen-client-fetch/src/parts/ActionFunc.ts, packages/openapi-codegen-client-fetch/src/parts/DocumentType.test.ts, packages/openapi-codegen-client-fetch/src/parts/IndexFile.ts, packages/openapi-codegen-client-fetch/src/parts/ResourceType.ts, packages/openapi-codegen-client-fetch/src/parts/UtilsFile.ts, packages/openapi-codegen-test-utils/src/context.ts, packages/openapi-codegen-utils/src/assert.ts, packages/openapi-codegen-utils/src/context.ts, packages/openapi-codegen-utils/src/openapi.ts
This PR extends client-fetch code generator to generate "raw" actions, which do not parse response bodies.
Adding the following annotation to OpenAPI operation
```yaml
/login:
post:
operationId: login
x-fresha-codegen:
client-fetch:
return: response
```
will makes the generated action look like:
```ts
export const login = (body: LoginRequest): Promise<Response> => {
...
};
```
N/A.
=> Openapi codegen client fetch improvement

packages/openapi-codegen-client-fetch/src/parts/DocumentType.test.ts, packages/openapi-codegen-client-fetch/src/parts/DocumentType.ts
This PR fixes a bug in `client-fetch` code generator. When the same JSON:API resource was used in multiple documents as their primary data, only the first document had proper type generated. The rest had generic `JSONAPIServerResource` instead.
N/A.
=> Handle case when the same JSON:API resource is used in multiple documents

packages/openapi-codegen-client-fetch/src/parts/ActionFunc.test.ts, packages/openapi-codegen-client-fetch/src/parts/ActionFunc.ts, packages/openapi-codegen-client-fetch/src/parts/UtilsFile.ts
This PR extends `client-fetch` code generator. The client libraries generated by it allow supplying custom `fetch()` implementation, instead of always using `global.fetch`. This simplifies testing of the code that uses client libraries.
At the moment type definition of the `fetcher` function is identical to that of browser `fetch()`. In next release, it will be defined more precisely as a common subset of node-fetch and browser fetch.
=> Allow custom fetch() function in generated fetch-based clients

packages/json-api-model/src/RelationshipSchema.test.ts, packages/openapi-codegen-client-fetch/src/parts/ActionFunc.test.ts, packages/openapi-codegen-client-fetch/src/parts/DocumentType.test.ts, packages/openapi-codegen-server-nestjs/src/DTO.test.ts, packages/openapi-codegen-server-nestjs/src/Generator.test.ts, packages/openapi-codegen-utils/src/jsonapi.ts, packages/openapi-model/src/3.0.3/model/OpenAPIReader.ts, packages/openapi-model/src/3.0.3/model/OpenAPIWriter.test.ts, packages/openapi-model/src/3.0.3/model/Schema.test.ts, packages/openapi-model/src/3.0.3/model/Schema.ts, packages/openapi-model/src/3.0.3/model/types.ts
This PR makes it more convenient to set up array-like schemas. Now it is possible to set array item schema directly, as:
```ts
schema.setProperty('data', 'array').setItems('object');
// now schema.setProperty has 'data' property which represents an array of object schemas
```
N/A.
=> Add SchemaModel.setItems() member

packages/json-api-model/src/ResourceSchema.ts, packages/json-api-model/src/types.ts, packages/openapi-codegen-utils/src/jsonapi.ts, packages/openapi-model/src/3.0.3/model/Components.test.ts, packages/openapi-model/src/3.0.3/model/Components.ts, packages/openapi-model/src/3.0.3/model/Schema.test.ts, packages/openapi-model/src/3.0.3/model/Schema.ts, packages/openapi-model/src/3.0.3/model/types.ts
This PR improves the experience of creating schema models. Now it is possible to pass extra options to `SchemaModel.create` and `ComponentsModel.setSchema`
SchemaModelFactory methods require some refactor, because there is duplicated code between `.create` and `.setProperty` methods.
=> Extend SchemaModelFactory.create and ComponentsModel.setSchema

packages/json-api-model/src/ResourceSchema.ts, packages/json-api-model/src/types.ts, packages/json-schema-model/src/types.ts, packages/openapi-codegen-utils/src/jsonapi.ts, packages/openapi-model/src/3.0.3/model/Components.ts, packages/openapi-model/src/3.0.3/model/MediaType.test.ts, packages/openapi-model/src/3.0.3/model/MediaType.ts, packages/openapi-model/src/3.0.3/model/Schema.test.ts, packages/openapi-model/src/3.0.3/model/Schema.ts, packages/openapi-model/src/3.0.3/model/types.test.ts, packages/openapi-model/src/3.0.3/model/types.ts
As described in https://github.com/fresha/api-tools/issues/60.
Public types were refined. Now we have 3 of them:
- `CreateSchemaOptions` - this should be accepted by methods that only create schemas. `ComponentsModel.setSchema` is a good example of such a method
- `CreateOrSetSchemaOptions` - this should be accepted by methods that can either create schemas, or using schemas passed from outside. `MediaType.setSchema` is an example of such a method.
- `CreateSchemaPropertyOptions` - this is used specifically by `SchemaModel.setProperty` and `SchemaModel.setProperties`. It is very similar to `CreateOrSetSchemaOptions`, except it allows for `required` property.
Methods' signatures were extended:
- …
=> Allow creating deep hierarchies of SchemaModel objects in schema properties

packages/openapi-codegen-client-fetch/src/parts/ActionFunc.test.ts, packages/openapi-codegen-client-fetch/src/parts/ActionFunc.ts, packages/openapi-codegen-client-fetch/src/parts/UtilsFile.ts
This PR makes it possible to:
- pass proxy-related headers in API client libraries generated by `client-fetch` codegen
- pass authorisation cookie on a per-request basis
N/A.
=> Implement extra call params in client-fetch codegen

packages/openapi-codegen-client-fetch/src/Generator.ts, packages/openapi-codegen-client-fetch/src/command.ts, packages/openapi-codegen-client-fetch/src/context.ts, packages/openapi-codegen-client-fetch/src/parts/IndexFile.ts, packages/openapi-codegen-client-fetch/src/parts/UtilsFile.ts, packages/openapi-codegen-client-fetch/src/testHelpers.ts, packages/openapi-codegen-utils/src/openapi.ts
This PR improves `client-fetch` code generator:
- generated code has better support of error handling
- ability to skip generating code for certain actions, based on their status (deprecated, internal) and tags
N/A.
=> Improve client fetch codegen

package-lock.json, packages/json-api-model/package.json, packages/json-api-model/src/RelationshipSchema.ts, packages/openapi-codegen-cli/package.json, packages/openapi-codegen-client-fetch/package.json, packages/openapi-codegen-client-fetch/src/parts/DocumentType.test.ts, packages/openapi-codegen-client-fetch/src/parts/DocumentType.ts, packages/openapi-codegen-client-fetch/src/parts/ResourceType.ts, packages/openapi-codegen-client-fetch/src/parts/utils.ts, packages/openapi-codegen-client-fresha/package.json, packages/openapi-codegen-docs/package.json, packages/openapi-codegen-docs/src/parts/Generator.ts, packages/openapi-codegen-server-elixir/package.json, packages/openapi-codegen-server-elixir/src/parts/Action.ts, packages/openapi-codegen-server-mock/package.json, packages/openapi-codegen-server-nestjs/package.json, packages/openapi-codegen-server-nestjs/src/DTO.ts, packages/openapi-codegen-test-utils/package.json, packages/openapi-codegen-utils/package.json, packages/openapi-lint/package.json, packages/openapi-lint/src/rules/oas3/noUnusedSharedComponents.ts, packages/openapi-model/examples/json-api.yaml, packages/openapi-model/package.json, packages/openapi-model/src/3.0.3/model/OpenAPIReader.ts, packages/openapi-model/src/3.0.3/model/OpenAPIWriter.ts, packages/openapi-model/src/3.0.3/model/Schema.test.ts, packages/openapi-model/src/3.0.3/model/Schema.ts, packages/openapi-model/src/3.0.3/model/types.ts, packages/openapi-model/src/3.0.3/types.ts
This PR extends `SchemaModel` with support for tuple-like schemas, like:
```yaml
SomeSchema:
type: array
items:
- type: boolean
- type: string
```
=> Add support for tuple-like schema models

packages/openapi-codegen-client-fetch/src/parts/UtilsFile.ts
This PR fixes a bug in the code generated by client-fetch codegen. Instead of checking the authorisation cookie every time and in every environment (browser, Node.js), it now only checked on Node.js.
Before:
```ts
init({ ... });
setAuthCookie('name', 'value'); // had to do this, even if the cookie was not used
```
Now (browsers):
```ts
init({ ... });
// setAuthCookie is not needed because the cookie is added implicitly by credentials: 'include'
```
=> Code generated by client-fetch checks cookie only on nodejs

packages/openapi-codegen-client-fetch/src/parts/ActionFunc.test.ts, packages/openapi-codegen-client-fetch/src/parts/ActionFunc.ts, packages/openapi-codegen-client-fetch/src/parts/UtilsFile.ts
This PR extends the code generated by `client-fetch` code generator. Now it is possible to set a 'success callback' - a function that gets called after API call succeeds. It accepts the list of parameters passed to the action as well as the response obtained from the server.
The flagship use case for this functionality would be integration with Redux.
Usage:
```ts
const successCallback = (params: unknown, response: JSONValue): void => {
store.dispatch({
type: JSON_API_ORM_UPDATE,
payload: {
params,
response,
},
});
};
init({
fetcher: global.fetch,
rootUrl: 'https://api.example.com',
successCallback,
});
```
Naming may not be fully optimal.
=> Add success callback to the code generated by client-fetch codegen

packages/openapi-codegen-client-fetch/src/parts/ActionFunc.test.ts, packages/openapi-codegen-client-fetch/src/parts/ActionFunc.ts
This PR fixes a bug in client-fetch codegen. Before, the generated fetch() calls contained HTPP method names in lowercase (e.g. get, post), whereas they must be in upper case.
N/A.
=> Use upper case method names in fetch()

tools/typescript-config/tsconfig.json
With current settings, usage of e.g. private class fields results in a lot of superfluous code generated. At the same time, Node 18.x (current LTS), which is the primary runtime for this package, supports most of these features natively.
This PR changes the transpiration target from ES2020 to ES2022. This will allow to use
- private class fields
- class / static fields
- top-level await
as have optimally transpiled code.
N/A.
=> Set the TS transpilation target to ES2022

packages/openapi-codegen-server-elixir/src/parts/Action.ts, packages/openapi-codegen-server-elixir/src/parts/Controller.test.ts, packages/openapi-codegen-server-elixir/src/parts/ResourceTestSuite.test.ts, packages/openapi-codegen-server-elixir/src/parts/ResourceTestSuite.ts, packages/openapi-codegen-server-nestjs/src/DTO.test.ts, packages/openapi-codegen-server-nestjs/src/DTO.ts, packages/openapi-codegen-utils/src/openapi.test.ts, packages/openapi-codegen-utils/src/openapi.ts, packages/openapi-diff/src/Differ.ts, packages/openapi-model/examples/json-api.yaml, packages/openapi-model/src/3.0.3/model/OpenAPIReader.test.ts, packages/openapi-model/src/3.0.3/model/OpenAPIReader.ts, packages/openapi-model/src/3.0.3/model/OpenAPIWriter.ts, packages/openapi-model/src/3.0.3/model/Schema.test.ts, packages/openapi-model/src/3.0.3/model/Schema.ts, packages/openapi-model/src/3.0.3/model/types.ts, packages/openapi-model/src/3.0.3/types.ts
There are several discrepancies between the [JSON Schema for OpenAPI 3.0.3](https://github.com/OAI/OpenAPI-Specification/blob/main/schemas/v3.0/schema.yaml) and current implementation in `@fresha/openapi-model`:
- `exclusiveMinimum` and `exclusiveMaximum` must be booleans
- `items` cannot be an array of schemas
This PR fixes these issues. It also adds a couple of (previously missing) tests for Elixir / NestJS codegens.
N/A.
=> Make SchemaModel/SchemaObject compatible with JSON Schema for OpenAPI 3.0.3

examples/openapi-codegen-test-api.yaml, packages/openapi-codegen-client-fetch/src/parts/ActionFunc.test.ts, packages/openapi-codegen-client-fetch/src/parts/ActionFunc.ts
Currently, `client-fetch` codegen incorrectly generates code for actions without parameters. Namely, it calls `successCallback(params, response)` where `params` is undefined.
This PR fixes this behaviour. Now, actions without parameters call success callback as `successCallback(undefined, response)`.
N/A.
=> Correctly handle actions w/o parameters in client-fetch codegen

packages/openapi-codegen-client-fetch/src/parts/ActionFunc.test.ts, packages/openapi-codegen-client-fetch/src/parts/ActionFunc.ts, packages/openapi-codegen-client-fetch/src/parts/UtilsFile.ts
Inside `successCallback` function in the code generated by `client-fetch` generator, it is not possible to learn which action has been called. Therefore, it is not possible to do something different for different API actions.
This PR changes signature of the `successCallback` to `(actionName: string, params: unknown, response: JSONValue) => void`. 
N/A.
=> client-fetch codegen passes action name to successCallback

packages/openapi-codegen-client-fetch/src/Generator.ts, packages/openapi-codegen-client-fetch/src/context.ts, packages/openapi-codegen-client-fetch/src/parts/ActionFunc.test.ts, packages/openapi-codegen-client-fetch/src/parts/ActionFunc.ts, packages/openapi-codegen-client-fetch/src/parts/DocumentType.test.ts, packages/openapi-codegen-client-fetch/src/parts/DocumentType.ts, packages/openapi-codegen-client-fetch/src/parts/IndexFile.ts, packages/openapi-codegen-client-fetch/src/parts/ResourceType.test.ts, packages/openapi-codegen-client-fetch/src/parts/ResourceType.ts, packages/openapi-codegen-client-fetch/src/testHelpers.ts
This PR makes the client-fetch code generator to generate request / response types in a separate file named `src/types.ts`. For client library users this change should be transparent.
N/A.
=> Generate OpenAPI client types in a separate file

packages/openapi-codegen-client-fetch/src/parts/ActionFunc.test.ts, packages/openapi-codegen-client-fetch/src/parts/ActionFunc.ts, packages/openapi-codegen-client-fetch/src/parts/DocumentType.test.ts, packages/openapi-codegen-client-fetch/src/parts/DocumentType.ts, packages/openapi-codegen-client-fetch/src/parts/ResourceType.test.ts, packages/openapi-codegen-client-fetch/src/parts/ResourceType.ts
This PR extends client fetch codegen with JSDoc documentation blocks. This improves IDE support when working with client libraries.
N/A.
=> Add JSDoc blocks to action functions, request and response types

packages/openapi-codegen-client-fetch/src/Generator.ts, packages/openapi-codegen-client-fetch/src/command.ts, packages/openapi-codegen-client-fetch/src/context.ts, packages/openapi-codegen-client-fetch/src/parts/DocumentType.ts, packages/openapi-codegen-client-fetch/src/parts/IndexFile.ts, packages/openapi-codegen-client-fetch/src/parts/NamedType.ts, packages/openapi-codegen-client-fetch/src/parts/RequestFormatterFunc.test.ts, packages/openapi-codegen-client-fetch/src/parts/RequestFormatterFunc.ts, packages/openapi-codegen-client-fetch/src/parts/ResourceType.ts, packages/openapi-codegen-client-fetch/src/parts/index.ts, packages/openapi-codegen-client-fetch/src/testHelpers.ts, packages/openapi-model/src/3.0.3/model/Schema.ts, packages/openapi-model/src/3.0.3/model/types.ts
For JSON:API clients, building request bodies is a tedious and error-prone task, even with complete types. This PR extends the `client-fetch` code generator with the ability to generate functions that format request bodies.
`client-fetch` generates formatters when it is invoked with the `--with-formatters` options. This is done for compatibility reasons, but will change in future versions.
All request formatter functions are placed in the `src/formatters.ts` file.
A request formatter function is generated for each requestBody defined. For JSON:API requests, they accept simplified representation of request data:
- attributes and relationships are put into the same object
- relationship data is an ID or …
=> Implement generation of request formatters in client-fetch

package-lock.json, packages/openapi-diff/package.json, packages/openapi-diff/src/Differ.ts, packages/openapi-diff/src/index.ts
This PR improves fresha-openapi-diff in two areas:
- it correctly increments versions if the target has been changed
- when using `--update-version`, it preserves the order of attributes from original schema file (before, it messed them)
N/A.
=> Improve fresha-openapi-diff logic and output

packages/openapi-diff/jest.config.js, packages/openapi-diff/package.json, packages/openapi-diff/src/index.ts, packages/openapi-diff/src/model/Differ.test.ts, packages/openapi-diff/src/model/Differ.ts, packages/openapi-diff/src/model/index.ts, packages/openapi-diff/src/model/types.ts, packages/openapi-model/src/3.0.3/model/Components.ts, packages/openapi-model/src/3.0.3/model/types.ts
Currently the code that produces a diff between two OpenAPI schemas is tightly connected with the code that maps diffs to versions. This makes it very difficult to handle cases where a breaking change in a schema does not mean a breaking changes in e.g. a client library built from it.
This PR aims to improve the situation.
Test coverage of the new code is ~40%, which needs more unit tests. Will add them in subsequent PRs.
=> Separate algorithms for OpenAPI diffing from version matching

packages/openapi-codegen-client-fetch/src/parts/ActionFunc.test.ts, packages/openapi-codegen-client-fetch/src/parts/ActionFunc.ts
When I made a header parameter optional in the refresh schema the client libraries failed to build with a type error
This PR aims to fix this issue
here is the original error
https://github.com/surgeventures/system/actions/runs/4532203561/jobs/7983379313?pr=55153
=> Allow optional header parameters

packages/openapi-codegen-client-fetch/package.json, packages/openapi-codegen-client-fetch/src/parts/ActionFunc.test.ts, packages/openapi-codegen-client-fetch/src/parts/DocumentType.test.ts, packages/openapi-codegen-client-fetch/src/parts/DocumentType.ts, packages/openapi-codegen-client-fetch/src/parts/IndexFile.test.ts, packages/openapi-codegen-client-fetch/src/parts/RequestFormatterFunc.test.ts, packages/openapi-codegen-client-fetch/src/parts/ResourceType.test.ts, packages/openapi-codegen-client-fetch/src/parts/UtilsFile.test.ts, packages/openapi-codegen-client-fetch/src/parts/__snapshots__/DocumentType.test.ts.snap, packages/openapi-codegen-client-fetch/src/parts/__snapshots__/IndexFile.test.ts.snap, packages/openapi-codegen-client-fetch/src/parts/__snapshots__/RequestFormatterFunc.test.ts.snap, packages/openapi-codegen-client-fetch/src/parts/__snapshots__/ResourceType.test.ts.snap, packages/openapi-codegen-client-fetch/src/parts/__snapshots__/UtilsFile.test.ts.snap, packages/openapi-codegen-client-fetch/src/parts/utils.test.ts
In short, this PR changes the way we write tests for `@fresha/openapi-codegen-client-fetch`. The biggest change is replacement of `.toHaveFormattedTypeScriptTest` with Jest snapshots. Besides that, I:
- deduplicated test preparation code by moving creation of often used objects to `beforeEach` blocks.
- added a couple of missing tests
- enabled a test coverage threshold for this package (total of 80% of functions/branches/statements).
These changes reduce the amount of code needed to write a codegen test, thus simplifying their creation.
N/A.
=> Improve test coverage in codegen client fetch

packages/openapi-model/jest.config.js, packages/openapi-model/src/3.0.3/model/OpenAPI.ts, packages/openapi-model/src/3.0.3/model/OpenAPIReader.test.ts, packages/openapi-model/src/3.0.3/model/Parameter/CookieParameter.test.ts, packages/openapi-model/src/3.0.3/model/Parameter/CookieParameter.ts, packages/openapi-model/src/3.0.3/model/Parameter/HeaderParameter.test.ts, packages/openapi-model/src/3.0.3/model/Parameter/HeaderParameter.ts, packages/openapi-model/src/3.0.3/model/Parameter/ParameterBase.test.ts, packages/openapi-model/src/3.0.3/model/Parameter/ParameterBase.ts, packages/openapi-model/src/3.0.3/model/Parameter/PathParameter.test.ts, packages/openapi-model/src/3.0.3/model/Parameter/PathParameter.ts, packages/openapi-model/src/3.0.3/model/Parameter/QueryParameter.test.ts, packages/openapi-model/src/3.0.3/model/Parameter/QueryParameter.ts, packages/openapi-model/src/3.0.3/model/Paths.test.ts, packages/openapi-model/src/3.0.3/model/Paths.ts, packages/openapi-model/src/3.0.3/model/Response.test.ts, packages/openapi-model/src/3.0.3/model/Response.ts, packages/openapi-model/src/3.0.3/model/SecurityScheme/APIKeySecurityScheme.test.ts, packages/openapi-model/src/3.0.3/model/SecurityScheme/APIKeySecurityScheme.ts, packages/openapi-model/src/3.0.3/model/SecurityScheme/OpenIdConnectSecurityScheme.test.ts, packages/openapi-model/src/3.0.3/model/SecurityScheme/OpenIdConnectSecurityScheme.ts, packages/openapi-model/src/3.0.3/model/ServerVariable.test.ts, packages/openapi-model/src/3.0.3/model/ServerVariable.ts, packages/openapi-model/src/3.0.3/model/Tag.test.ts, packages/openapi-model/src/3.0.3/model/XML.test.ts, packages/openapi-model/src/3.0.3/model/types.ts
This PR improves test coverage of the `@fresha/openapi-model` package, and makes it possible to set the coverage threshold to 70% (branch) and 80% (lines or functions).
Apart from more tests, I fixed several smaller bugs in property setters.
N/A.
=> Improve test coverage in openapi-model

packages/openapi-model/jest.config.js, packages/openapi-model/src/3.0.3/model/Components.test.ts, packages/openapi-model/src/3.0.3/model/Components.ts, packages/openapi-model/src/3.0.3/model/OpenAPIReader.test.ts, packages/openapi-model/src/3.0.3/model/OpenAPIReader.ts, packages/openapi-model/src/3.0.3/model/OpenAPIWriter.test.ts, packages/openapi-model/src/3.0.3/model/OpenAPIWriter.ts, packages/openapi-model/src/3.0.3/model/Operation.test.ts, packages/openapi-model/src/3.0.3/model/SecurityScheme/HTTPSecurityScheme.ts, packages/openapi-model/src/3.0.3/model/SecurityScheme/OpenIdConnectSecurityScheme.test.ts, packages/openapi-model/src/3.0.3/model/SecurityScheme/SecuritySchemeBase.ts, packages/openapi-model/src/3.0.3/model/types.ts, packages/openapi-model/src/3.0.3/types.ts, packages/openapi-model/src/3.1.0/types.ts, packages/openapi-model/src/shared/types.ts, tools/jest-config/src/index.ts
This PR improves test coverage of `OpenAPIReader` class in the `@fresha/openapi-model` to 80+ % in all categories, which allowed to put a global coverage thresholds to 80%.
Apart from tests, this PR fixes several bugs:
- `HTTPSecurityScheme#scheme` field type changed from `SchemaModel` to string enumeration `HTTPAuthSchema`, to be compatible with OpenAPI specification
- `Components#setSecuritySchema` for `HTTP` and `OpenIDConnect` security schemas now require additional parameters, specific to schemas
- `SecuritySchemeType` was moved from `./models/types.ts` to `shared/types.ts`.
Finally, I removed commented code from the `OpenAPIReader.test.ts` file.
More information on things that require more …
=> Improve test coverage and fix bugs in openapi-model

packages/openapi-lint/src/rules/oas3/serverList.ts
This PR fixes a bug in `fresha-openapi-lint`, which resulted in an error about empty server list even when it was not.
N/A.
=> Correctly check for server count in an OpenAPI schema

packages/openapi-codegen-client-fetch/src/parts/utils.test.ts, packages/openapi-codegen-client-fetch/src/parts/utils.ts
Currently, object types are not supported for parameters and resource attributes. This PR fixes this issue.
`schemaToType` builds a type definition for `object` schemas.
=> schemaToType supports object schemas

packages/openapi-codegen-client-fetch/src/parts/ActionFunc.ts, packages/openapi-codegen-client-fetch/src/parts/__snapshots__/ActionFunc.test.ts.snap
Currently, `client-fetch` codegen produces code with unused import. `utils/addQueryParam` is imported by `actions.ts` if an action has any parameter. It should be imported only if the action has a query parameter. This PR fixes that bug.
N/A.
=> Do not import addQueryParam unnecessarily

package-lock.json, packages/openapi-codegen-cli/src/index.ts, packages/openapi-codegen-client-fetch/src/context.ts, packages/openapi-codegen-client-fetch/src/parts/ActionFunc.ts, packages/openapi-codegen-client-fetch/src/parts/DocumentType.ts, packages/openapi-codegen-client-fetch/src/parts/RequestFormatterFunc.ts, packages/openapi-codegen-client-fetch/src/parts/ResourceType.ts, packages/openapi-codegen-client-fetch/src/parts/UtilsFile.ts, packages/openapi-codegen-client-fetch/src/parts/__snapshots__/ActionFunc.test.ts.snap, packages/openapi-codegen-client-fetch/src/parts/__snapshots__/ResourceType.test.ts.snap, packages/openapi-codegen-client-fetch/src/parts/__snapshots__/UtilsFile.test.ts.snap, packages/openapi-codegen-client-fetch/src/parts/index.ts, packages/openapi-codegen-client-fetch/src/parts/utils.test.ts, packages/openapi-codegen-client-fetch/src/parts/utils.ts, packages/openapi-lint/src/rules/oas3/noUnusedSharedComponents.ts
This PR improves the `client-fetch` code generator.
1. If a command fails, no code dump is printed on the console, only the error message. In verbose more, it also prints the stack trace. But not the dump of minified source code.
2. Generated resource types now have properly formatted property names. Before, property names of nested structures were always in the "schema" convention. Now they are properly converted to "client" convention. Also, generated names are quoted only when necessary (e.g. `someId` field will not be quoted in the generated code, only `'some-id'` will)  
3. A requirement on JSON:API resource types schemas has been relaxed. Now, if a schema defines multiple possible resource types (which we have in our legacy schemas), the first one is used. This allows a safe path …
=> Improve TS code generator

packages/api-tools-core/src/types.ts, packages/api-tools-core/src/utils.test.ts, packages/api-tools-core/src/utils.ts, packages/openapi-codegen-client-fetch/src/parts/ActionFunc.ts, packages/openapi-codegen-client-fetch/src/parts/IndexFile.ts, packages/openapi-codegen-client-fetch/src/parts/RequestFormatterFunc.test.ts, packages/openapi-codegen-client-fetch/src/parts/RequestFormatterFunc.ts, packages/openapi-codegen-client-fetch/src/parts/UtilsFile.ts, packages/openapi-codegen-client-fetch/src/parts/__snapshots__/ActionFunc.test.ts.snap, packages/openapi-codegen-client-fetch/src/parts/__snapshots__/IndexFile.test.ts.snap, packages/openapi-codegen-client-fetch/src/parts/__snapshots__/RequestFormatterFunc.test.ts.snap, packages/openapi-codegen-client-fetch/src/parts/__snapshots__/UtilsFile.test.ts.snap, packages/openapi-codegen-client-fetch/src/parts/utils.ts
This PR fixes the following bugs in TS client library generator:
- `camelCase()` now properly makes the first letter of the first word lowercase. I.e., `Team-name` would be transformed to teamName`, not to `TeamName` as currently.
- `jsonapi` field in definitions of JSON:API document types is now optional, as per spec
- fixed a typo in the name of the formatters module in client libraries. `fromatters` -> `formatters`
- request formatters in now abide to naming conventions specified
Also, to reduce the amount of duplicated JS documentation, `ExtraCallParams` is now documented once, in-place, and linked from action functions.
N/A.
=> Improve request formatters

packages/openapi-codegen-client-fetch/src/parts/ActionFunc.test.ts, packages/openapi-codegen-client-fetch/src/parts/ActionFunc.ts, packages/openapi-codegen-client-fetch/src/parts/RequestFormatterFunc.ts, packages/openapi-codegen-client-fetch/src/parts/ResourceType.ts, packages/openapi-codegen-client-fetch/src/parts/__snapshots__/ActionFunc.test.ts.snap
This PR fixes a bug, related to incorrectly interpolating values of path parameters in the code generated by `client-fetch` generator.
Before, if the client naming conventions were different from that of API, parameters did not interpolate.
```ts
const url = makeUrl(`/some/{obj-id}`); // incorrect, action parameter is named objId
```
new behaviour is the following:
```ts
const url = makeUrl(`/some/${params.objId}`); // correct
```
N/A.
=> Fix parameter interpolations in generated code
